import { InputSignature, TYPE_ANY, TYPE_ARRAY, TYPE_NUMBER, TYPE_OBJECT, TYPE_STRING } from '@metrichor/jmespath';

export const SUPPORTED_FUNCTIONS: [string, InputSignature[] | null][] = [
  // Array
  ['chunk', [{ types: [TYPE_ARRAY] }, { types: [TYPE_NUMBER], optional: true }]],
  ['compact', [{ types: [TYPE_ARRAY] }]],
  ['concat', [{ types: [TYPE_ARRAY] }, { types: [TYPE_ANY], optional: true, variadic: true }]],
  ['difference', [{ types: [TYPE_ARRAY] }, { types: [TYPE_ARRAY], optional: true }]],
  [
    'differenceBy',
    [{ types: [TYPE_ARRAY] }, { types: [TYPE_ARRAY], optional: true }, { types: [TYPE_ANY], optional: true }],
  ],
  // ['differenceWith', null],
  ['drop', [{ types: [TYPE_ARRAY] }, { types: [TYPE_NUMBER], optional: true }]],
  ['dropRight', [{ types: [TYPE_ARRAY] }, { types: [TYPE_NUMBER], optional: true }]],
  ['dropRightWhile', [{ types: [TYPE_ARRAY] }, { types: [TYPE_ARRAY, TYPE_STRING, TYPE_OBJECT], optional: true }]],
  ['dropWhile', [{ types: [TYPE_ARRAY] }, { types: [TYPE_ARRAY, TYPE_STRING, TYPE_OBJECT], optional: true }]],
  [
    'fill',
    [
      { types: [TYPE_ARRAY] },
      { types: [TYPE_ANY] },
      { types: [TYPE_NUMBER], optional: true },
      { types: [TYPE_NUMBER], optional: true },
    ],
  ],
  ['findIndex', null],
  ['findLastIndex', null],
  ['first', null],
  ['flatten', null],
  ['flattenDeep', null],
  ['flattenDepth', null],
  ['fromPairs', null],
  ['head', null],
  ['indexOf', null],
  ['initial', null],
  ['intersection', null],
  ['intersectionBy', null],
  ['intersectionWith', null],
  ['join', null],
  ['last', null],
  ['lastIndexOf', null],
  ['nth', null],
  ['pull', null],
  ['pullAll', null],
  ['pullAllBy', null],
  ['pullAllWith', null],
  ['pullAt', null],
  ['remove', null],
  ['reverse', null],
  ['slice', null],
  ['sortedIndex', null],
  ['sortedIndexBy', null],
  ['sortedIndexOf', null],
  ['sortedLastIndex', null],
  ['sortedLastIndexBy', null],
  ['sortedLastIndexOf', null],
  ['sortedUniq', null],
  ['sortedUniqBy', null],
  ['tail', null],
  ['take', null],
  ['takeRight', null],
  ['takeRightWhile', null],
  ['takeWhile', null],
  ['union', null],
  ['unionBy', null],
  ['unionWith', null],
  ['uniq', null],
  ['uniqBy', null],
  ['uniqWith', null],
  ['unzip', null],
  ['unzipWith', null],
  ['without', null],
  ['xor', null],
  ['xorBy', null],
  ['xorWith', null],
  ['zip', null],
  ['zipObject', null],
  ['zipObjectDeep', null],
  ['zipWith', null],

  // Collection
  ['countBy', null],
  ['each', null],
  ['eachRight', null],
  ['every', null],
  ['filter', null],
  ['find', null],
  ['findLast', null],
  ['flatMap', null],
  ['flatMapDeep', null],
  ['flatMapDepth', null],
  ['forEach', null],
  ['forEachRight', null],
  ['groupBy', null],
  ['includes', null],
  ['invokeMap', null],
  ['keyBy', null],
  ['map', null],
  ['orderBy', null],
  ['partition', null],
  ['reduce', null],
  ['reduceRight', null],
  ['reject', null],
  ['sample', null],
  ['sampleSize', null],
  ['shuffle', null],
  ['size', null],
  ['some', null],
  ['sortBy', null],

  // // Date
  //   'now',

  // // Function
  //   'after',
  //   'ary',
  //   'before',
  //   'bind',
  //   'bindKey',
  //   'curry',
  //   'curryRight',
  //   'debounce',
  //   'defer',
  //   'delay',
  //   'flip',
  //   'memoize',
  //   'negate',
  //   'once',
  //   'overArgs',
  //   'partial',
  //   'partialRight',
  //   'rearg',
  //   'rest',
  //   'spread',
  //   'throttle',
  //   'unary',
  //   'wrap',

  // Lang
  ['castArray', null],
  ['clone', null],
  ['cloneDeep', null],
  ['cloneDeepWith', null],
  ['cloneWith', null],
  ['conformsTo', null],
  ['eq', null],
  ['gt', null],
  ['gte', null],
  ['isArguments', null],
  ['isArray', null],
  ['isArrayBuffer', null],
  ['isArrayLike', null],
  ['isArrayLikeObject', null],
  ['isBoolean', null],
  ['isBuffer', null],
  ['isDate', null],
  ['isElement', null],
  ['isEmpty', null],
  ['isEqual', null],
  ['isEqualWith', null],
  ['isError', null],
  ['isFinite', null],
  ['isFunction', null],
  ['isInteger', null],
  ['isLength', null],
  ['isMap', null],
  ['isMatch', null],
  ['isMatchWith', null],
  ['isNaN', null],
  ['isNative', null],
  ['isNil', null],
  ['isNull', null],
  ['isNumber', null],
  ['isObject', null],
  ['isObjectLike', null],
  ['isPlainObject', null],
  ['isRegExp', null],
  ['isSafeInteger', null],
  ['isSet', null],
  ['isString', null],
  ['isSymbol', null],
  ['isTypedArray', null],
  ['isUndefined', null],
  ['isWeakMap', null],
  ['isWeakSet', null],
  ['lt', null],
  ['lte', null],
  ['toArray', null],
  ['toFinite', null],
  ['toInteger', null],
  ['toLength', null],
  ['toNumber', null],
  ['toPlainObject', null],
  ['toSafeInteger', null],
  ['toString', null],

  // Math
  ['add', null],
  ['ceil', null],
  ['divide', null],
  ['floor', null],
  ['max', null],
  ['maxBy', null],
  ['mean', null],
  ['meanBy', null],
  ['min', null],
  ['minBy', null],
  ['multiply', null],
  ['round', null],
  ['subtract', null],
  ['sum', null],
  ['sumBy', null],

  // Number
  ['clamp', null],
  ['inRange', null],
  ['random', null],

  // Object
  ['assign', null],
  ['assignIn', null],
  ['assignInWith', null],
  ['assignWith', null],
  ['at', null],
  ['create', null],
  ['defaults', null],
  ['defaultsDeep', null],
  ['entries', null],
  ['entriesIn', null],
  ['extend', null],
  ['extendWith', null],
  ['findKey', null],
  ['findLastKey', null],
  ['forIn', null],
  ['forInRight', null],
  ['forOwn', null],
  ['forOwnRight', null],
  ['functions', null],
  ['functionsIn', null],
  ['get', null],
  ['has', null],
  ['hasIn', null],
  ['invert', null],
  ['invertBy', null],
  ['invoke', null],
  ['keys', null],
  ['keysIn', null],
  ['mapKeys', null],
  ['mapValues', null],
  ['merge', null],
  ['mergeWith', null],
  ['omit', null],
  ['omitBy', null],
  ['pick', null],
  ['pickBy', null],
  ['result', null],
  ['set', null],
  ['setWith', null],
  ['toPairs', null],
  ['toPairsIn', null],
  ['transform', null],
  ['unset', null],
  ['update', null],
  ['updateWith', null],
  ['values', null],
  ['valuesIn', null],

  // // Seq
  //   'chain',
  //   'tap',
  //   'thru',
  //   'prototype'[Symbol.iterator],
  //   'prototype'.at,
  //   'prototype'.chain,
  //   'prototype'.commit,
  //   'prototype'.next,
  //   'prototype'.plant,
  //   'prototype'.reverse,
  //   'prototype'.toJSON,
  //   'prototype'.value,
  //   'prototype'.valueOf,

  // String
  ['camelCase', null],
  ['capitalize', null],
  ['deburr', null],
  ['endsWith', null],
  ['escape', null],
  ['escapeRegExp', null],
  ['kebabCase', null],
  ['lowerCase', null],
  ['lowerFirst', null],
  ['pad', null],
  ['padEnd', null],
  ['padStart', null],
  ['parseInt', null],
  ['repeat', null],
  ['replace', null],
  ['snakeCase', null],
  ['split', null],
  ['startCase', null],
  ['startsWith', null],
  ['template', null],
  ['toLower', null],
  ['toUpper', null],
  ['trim', null],
  ['trimEnd', null],
  ['trimStart', null],
  ['truncate', null],
  ['unescape', null],
  ['upperCase', null],
  ['upperFirst', null],
  ['words', null],

  // Util
  ['attempt', null],
  ['bindAll', null],
  ['cond', null],
  ['conforms', null],
  ['constant', null],
  ['defaultTo', null],
  ['flow', null],
  ['flowRight', null],
  ['identity', null],
  ['iteratee', null],
  ['matches', null],
  ['matchesProperty', null],
  ['method', null],
  ['methodOf', null],
  ['mixin', null],
  ['noConflict', null],
  ['noop', null],
  ['nthArg', null],
  ['over', null],
  ['overEvery', null],
  ['overSome', null],
  ['property', null],
  ['propertyOf', null],
  ['range', null],
  ['rangeRight', null],
  ['runInContext', null],
  ['stubArray', null],
  ['stubFalse', null],
  ['stubObject', null],
  ['stubString', null],
  ['stubTrue', null],
  ['times', null],
  ['toPath', null],
  ['uniqueId', null],
];
